# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 2.7
install: pip install -r requirements/dev.txt
services:
  - postgresql
before_script:
  - psql -c 'create database wordfor_test;' -U postgres
  - psql -c "create user wordfor with superuser password 'wordfor123';" -U postgres
script: python manage.py test
