# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 2.7
install: pip install -r requirements/dev.txt
services:
  - postgresql
before_script:
  - psql -c 'create database wpiifc_test;' -U postgres
  - psql -c "create user wpiifc with superuser password 'wpiifc123';" -U postgres
  - npm install
  - ./node_modules/.bin/bower install
script: python manage.py test
