"""Adds preuser.school_title column to the db.

Revision ID: 06299bfd31e3
Revises: d2a3b14d6a89
Create Date: 2016-12-14 00:37:56.603266

"""

# revision identifiers, used by Alembic.
revision = '06299bfd31e3'
down_revision = 'd2a3b14d6a89'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preusers', sa.Column('school_title', sa.String(length=120), nullable=True))

    op.execute("UPDATE preusers SET school_title='Worcester Polytechnic Institute';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preusers', 'school_title')
    # ### end Alembic commands ###
