"""Adds guests.entered_party_at and guests.left_party_at columns.

Revision ID: 0e62c8d2e456
Revises: 868c6b0b0054
Create Date: 2016-11-28 20:38:40.540276

"""

# revision identifiers, used by Alembic.
revision = '0e62c8d2e456'
down_revision = '868c6b0b0054'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('entered_party_at', sa.DateTime(), nullable=True))
    op.add_column('guests', sa.Column('left_party_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'left_party_at')
    op.drop_column('guests', 'entered_party_at')
    # ### end Alembic commands ###
