"""Creates the guests table

Revision ID: 38dbe9301b4c
Revises: 6451c45cc96d
Create Date: 2016-04-21 09:38:28.846577

"""

# revision identifiers, used by Alembic.
revision = '38dbe9301b4c'
down_revision = '6451c45cc96d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('is_at_party', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guests')
    ### end Alembic commands ###
