"""Creates the preregistered users table.

Revision ID: 51127a724825
Revises: cf49f49a2c66
Create Date: 2016-04-11 12:50:39.023519

"""

# revision identifiers, used by Alembic.
revision = '51127a724825'
down_revision = 'cf49f49a2c66'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('chapter_admin', sa.Boolean(), nullable=True),
    sa.Column('ifc_admin', sa.Boolean(), nullable=True),
    sa.Column('fraternity_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preusers')
    ### end Alembic commands ###
