"""Adds capacities table for users.

Revision ID: 58c968a5c213
Revises: a2c99320aae4
Create Date: 2017-12-29 18:53:26.489653

"""

# revision identifiers, used by Alembic.
revision = '58c968a5c213'
down_revision = 'a2c99320aae4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capacities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('male_max', sa.Integer(), nullable=True),
    sa.Column('female_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'users', sa.Column('capacity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'capacities', ['capacity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column(u'users', 'capacity_id')
    op.drop_table('capacities')
    # ### end Alembic commands ###
