"""Changes the user-role relationship to a one-to-many relationship

Revision ID: 7cc0f8aca352
Revises: ead74654b223
Create Date: 2016-03-31 21:21:19.345250

"""

# revision identifiers, used by Alembic.
revision = '7cc0f8aca352'
down_revision = 'ead74654b223'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'roles_user_id_fkey', 'roles', type_='foreignkey')
    op.drop_column('roles', 'user_id')
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.add_column('roles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'roles_user_id_fkey', 'roles', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###
