"""Adds gender to the guests table

Revision ID: c7409dde9162
Revises: 38dbe9301b4c
Create Date: 2016-04-21 23:51:23.557787

"""

# revision identifiers, used by Alembic.
revision = 'c7409dde9162'
down_revision = '38dbe9301b4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('is_male', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'is_male')
    ### end Alembic commands ###
