"""empty message

Revision ID: cc3b6c92f663
Revises: d5bbb68e3d38
Create Date: 2016-04-24 12:12:02.970228

"""

# revision identifiers, used by Alembic.
revision = 'cc3b6c92f663'
down_revision = 'd5bbb68e3d38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fraternities', 'can_have_parties',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fraternities', 'can_have_parties',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    ### end Alembic commands ###
