"""Adds a unique constraint of party_id/name to the guest table

Revision ID: ce7d019512b1
Revises: 0e62c8d2e456
Create Date: 2016-12-06 08:21:15.390607

"""

# revision identifiers, used by Alembic.
revision = 'ce7d019512b1'
down_revision = '0e62c8d2e456'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_name_party_uc', 'guests', ['name', 'party_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_party_uc', 'guests', type_='unique')
    ### end Alembic commands ###
