"""Adds schools to the database

Revision ID: d2a3b14d6a89
Revises: ce7d019512b1
Create Date: 2016-12-13 18:24:45.336983

"""

# revision identifiers, used by Alembic.
revision = 'd2a3b14d6a89'
down_revision = 'ce7d019512b1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker

from ifc.models import Fraternity, School

Session = sessionmaker()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('short_title', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )

    # create the initial school for the existing data
    bind = op.get_bind()
    session = Session(bind=bind)
    new_school = School(title="Worcester Polytechnic Institute",
                        short_title="WPI")
    session.add(new_school)

    op.add_column(u'fraternities', sa.Column('school_id', sa.Integer()))
    op.drop_constraint(u'fraternities_title_key', 'fraternities', type_='unique')
    op.create_foreign_key(None, 'fraternities', 'schools', ['school_id'], ['id'])

    # update the current fraternities to belong to the only school
    for frat in session.query(Fraternity):
        frat.school = new_school

    session.commit()

    op.alter_column('fraternities', 'school_id',
                    existing_type=sa.Integer(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fraternities', type_='foreignkey')
    op.create_unique_constraint(u'fraternities_title_key', 'fraternities', ['title'])
    op.drop_column(u'fraternities', 'school_id')
    op.drop_table('schools')
    # ### end Alembic commands ###
