"""Creates the party model

Revision ID: e2200226cabc
Revises: 51127a724825
Create Date: 2016-04-15 19:05:18.683241

"""

# revision identifiers, used by Alembic.
revision = 'e2200226cabc'
down_revision = '51127a724825'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parties')
    ### end Alembic commands ###
