"""Changes role.name to role.title and removes email and created_at from users

Revision ID: ead74654b223
Revises: e2f277e3f1c0
Create Date: 2016-03-31 20:56:33.461490

"""

# revision identifiers, used by Alembic.
revision = 'ead74654b223'
down_revision = 'e2f277e3f1c0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('title', sa.String(length=80), nullable=False))
    op.drop_constraint(u'roles_name_key', 'roles', type_='unique')
    op.create_unique_constraint(None, 'roles', ['title'])
    op.drop_column('roles', 'name')
    op.drop_constraint(u'users_email_key', 'users', type_='unique')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_unique_constraint(u'users_email_key', 'users', ['email'])
    op.add_column('roles', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_unique_constraint(u'roles_name_key', 'roles', ['name'])
    op.drop_column('roles', 'title')
    ### end Alembic commands ###
