"""empty message

Revision ID: efe2394273fe
Revises: c7409dde9162
Create Date: 2016-04-23 10:15:52.095061

"""

# revision identifiers, used by Alembic.
revision = 'efe2394273fe'
down_revision = 'c7409dde9162'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('started', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parties', 'started')
    ### end Alembic commands ###
